version: '3'

services:
  roomlottery:
    image: nginx:alpine
    container_name: roomlottery
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - nginx-proxy
    expose:
      - "80"
      - "443"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nginx-proxy
    ports:
      - "5432:5432"

  nodejs:
    image: node:latest
    container_name: nodejs
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    command: node server.js
    networks:
      - nginx-proxy
    ports:
      - "5000:5000"

networks:
  nginx-proxy:
    external: true

volumes:
  postgres_data:
